[general]
TELEGRAM_BOT_TOKEN = "8406344716:AAEK-hDnCaFDcUD_XtOAZwM7W60DBmwCZe0"
TELEGRAM_CHAT_ID = "5593618103"
DASHBOARD_URL = "https://myupstoxproject2-9irrjq8pewq8bedd9ouxk5.streamlit.app/"

UPSTOX_API_KEY = "8x22etry4k"
UPSTOX_ACCESS_TOKEN = "eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiJCUDY3NTUiLCJqdGkiOiI2ODgyM2RlMDFiZTE0ZTJiZjhiM2YzYWEiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6dHJ1ZSwiaWF0IjoxNzUzMzY1OTg0LCJpc3MiOiJ1ZGFwaS1nYXRld2F5LXNlcnZpY2UiLCJleHAiOjE3NTMzOTQ0MDB9.cy52yP2njvV53k6M7GaFVoYccdb5V0a9DEqlO54PyNI"
